Lesson2
ShakeYourMind4/lesson1 pull request #2
Opened 2024-04-07 20:52 UTC by ShakeYourMind4

2024-04-10 09:48 UTC, TsakunovR requested changes

2024-04-10 09:48 UTC, TsakunovR commented on core/contracts.py
> +# USER_DATA_SCHEMA = {
Почему эта схема закомментирована?

2024-04-10 09:48 UTC, TsakunovR commented on core/contracts.py
> +# USER_DATA_SCHEMA = {
Нужно разкоментировать

2024-04-11 16:33 UTC, ShakeYourMind4 commented on core/contracts.py
> +# USER_DATA_SCHEMA = {
А если у меня такое, что когда я разкоментировал, то у меня в этом файле получается две схемы. Но когда я запсукаю урок или домашку, то там выполняется только один тест, это норм?

2024-04-13 08:15 UTC, merged